import UsdtAbi from "../abis/USDT.json";
import FloppyAbi from "../abis/Floppy.json";
import BirdAbi from "../abis/Bird.json";
import BirdMarketPlace from "../abis/BirdMarketPlace.json";
import FLPCrowdSale from "../abis/FLPCrowdSale.json";
export const getUsdtAbi = () => UsdtAbi;
export const getFloppyAbi = () => FloppyAbi;
export const getBirdAbi = () => BirdAbi;
export const getBirdMarketPlaceAbi = () => BirdMarketPlace;
export const getFLPCrowdSaleABI = () => FLPCrowdSale;
